VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsTeam"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public DivisionName As String
Public DivisionLeader As String
Public DivisionLeaderEmail As String
Public TeamName As String
Public TeamLeader As String
Public AreaName As String
Public DictEmployees As Scripting.Dictionary
Public DivisionNameShort As String
Public SaveEmailPath As String
